Add merge conflict note to README file
electrovir/git-vir pull request #2
Opened 2024-04-15 17:11 UTC by KylerHansen

2024-04-15 17:14 UTC, electrovir requested changes

2024-04-15 17:14 UTC, electrovir commented on README.md
> +    - If you use a remote name besides `origin`, you can provide that as well with `git-vir <remote-name-here> push`
```suggestion
    - If you use a remote name besides `origin`, you can provide that as well with `git-vir <remote-name-here> push`.
```

2024-04-15 17:14 UTC, electrovir commented on README.md
> +    - If you encounter merge conflicts, resolve the conflicts, run `git-rebase --continue` until rebase has finished. Then, run `git-vir push` to resume updating the chain.
```suggestion
    - If you encounter merge conflicts, resolve them as you would for a normal `git rebase` command. Then run `git-vir push` to resume updating the chain.
```

2024-04-15 17:21 UTC, KylerHansen commented on README.md
> +    - If you use a remote name besides `origin`, you can provide that as well with `git-vir <remote-name-here> push`
added

2024-04-15 17:22 UTC, KylerHansen commented on README.md
> +    - If you encounter merge conflicts, resolve the conflicts, run `git-rebase --continue` until rebase has finished. Then, run `git-vir push` to resume updating the chain.
updated

2024-04-15 17:25 UTC, electrovir requested changes

2024-04-15 17:25 UTC, electrovir commented on README.md
> +    - If you encounter merge conflicts, resolve  them as you would for a normal `git rebase` command. Then, run `git-vir push` to resume updating the chain.
Sorry, just one last tiny change:
```suggestion
    - If you encounter merge conflicts, resolve them as you would for a normal `git rebase` command. Then, run `git-vir push` to resume updating the chain.
```

2024-08-15 17:08 UTC, electrovir commented
I'll fix this after merge

2024-08-15 17:08 UTC, electrovir commented on README.md
> +    - If you encounter merge conflicts, resolve  them as you would for a normal `git rebase` command. Then, run `git-vir push` to resume updating the chain.
I'll fix this after merge

2024-08-15 17:09 UTC, merged